Project/WebApplication3/Controllers/PublicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    
    public class PublicController : Controller
    {

        ShopTestContext context = new ShopTestContext();
        [AllowAnonymous]
        public IActionResult Index()
        {
            return RedirectToAction("Login");
        }

        public IActionResult Login()
        {
            string staffStr = HttpContext.Session.GetString("staff");
            if (staffStr == "" || staffStr == null)
            {
                ViewBag.username = TempData["username"];
                ViewBag.alter = TempData["alter"];
                return View();
            }
            return Redirect("../Home/Index");

        }

        
        [HttpPost]
        public IActionResult DoLogin(string username, string password)
        {
            staff staff = context.staff.Where(s => s.Username == username && s.Password == password).FirstOrDefault();

            if(staff == null)
            {
                TempData["alter"] = "Login faild";
                TempData["username"] = username;
                HttpContext.Session.SetString("staff", "");
                return RedirectToAction("Login");
            }
            else
            {
                string satffStr = JsonConvert.SerializeObject(staff);
                HttpContext.Session.SetString("staff", satffStr);

                TempData["alter"] = "";
                TempData["username"] = "";

                if(staff.Status == false)
                {
                    TempData["alter"] = "Account has been banned!";
                    TempData["username"] = username;
                    HttpContext.Session.SetString("staff", "");
                    return RedirectToAction("Login");
                }

                return Redirect("../Home/Index");
            }
        }

        public IActionResult Logout(string username, string password)
        {
            HttpContext.Session.SetString("staff", "");
            HttpContext.Session.SetString("cart", "");
            HttpContext.Session.SetString("cartImport", "");
            return Redirect("Login");
        }
    }
}

Project/WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/utitl.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SHOP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        <li class="nav-item" style="margin-left:800px">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Public" asp-action="Logout">Logout</a>
                        </li>*
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <div id="alter"></div>
    @await RenderSectionAsync("Scripts", required: false)

    @*
        <script>
            $(document).ready(function () {
                window.setTimeout(function () {
                    $("#success-alert").alert('close');
                }, 2000);
            });

            function getAlter() {
                var content = document.getElementById('alter');
                content.innerHTML = "<div class='alert alert-success' id='success-alert'> \n"
                    + " <button type='button' class='close' data-dismiss='alert'>x</button>\n"
                    + "<strong>Success!</strong>Product have added to your wishlist\n"
                    + "</div>"
            }
        </script>
    *@
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                "searching": false,
                "lengthMenu": false,
                'lengthChange': false
            });
        });
    </script>

</body>
</html>